# Numpy Introduction

NumPy is a powerful Python library for numerical computing. It stands for "Numerical Python" and provides efficient data structures, mathematical functions, and tools for working with large arrays and matrices. 

In [16]:
import numpy as np
np.__version__

'1.24.4'

## Create arrays from lists

In [17]:
a = np.array([2, 3, 4])
print(a)
print(a.shape)
type(a)

[2 3 4]
(3,)


numpy.ndarray

Get and set values

In [18]:
print(a[2])
a[2] = 9
print(a)

4
[2 3 9]


Two dimensional arrays

In [19]:
b = np.array([[2, 3, 4], [5, 6, 7]])
print(b)
print(b.shape)

[[2 3 4]
 [5 6 7]]
(2, 3)


Change values in 2d arrays

In [20]:
b[1, 2] = 9
print(b)

[[2 3 4]
 [5 6 9]]


Three dimensial array

In [21]:
c = np.array([[[2, 1, 2, 5], [4,2, 5, 2], [9, 8, 7, 6]],
              [[3,5, 4, 1], [8, 9, 2, 6], [0,1, 8, 8]]])
print(c)
print(c.shape)

[[[2 1 2 5]
  [4 2 5 2]
  [9 8 7 6]]

 [[3 5 4 1]
  [8 9 2 6]
  [0 1 8 8]]]
(2, 3, 4)


Change value in 3D array

In [22]:
c[0, 0, 0] = 11
print(c)

[[[11  1  2  5]
  [ 4  2  5  2]
  [ 9  8  7  6]]

 [[ 3  5  4  1]
  [ 8  9  2  6]
  [ 0  1  8  8]]]


You need to take care of the number of dimensions

In [23]:
c[2, 3] = 8

IndexError: index 2 is out of bounds for axis 0 with size 2

## Speial array constructors

In [24]:
# Empty array
a1 = np.zeros((3, 2))
print(a1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [25]:
# ones
a2 = np.ones((2, 3))
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [26]:
# constant
a3 = np.full((3, 3), 3.14)
print(a3)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [27]:
# identity
a4 = np.eye(3)
print(a4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# random
a5 = np.random.random((3, 2))
print(a5)

[[0.87925251 0.01659017]
 [0.13923025 0.89700516]
 [0.14659205 0.58185684]]


In [29]:
# ranges
print(np.arange(2, 14))
print(np.arange(0, 50, 5))

[ 2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  5 10 15 20 25 30 35 40 45]


## Indexing arrays

In [30]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Slicing

In [31]:
a[:2,1:3]

array([[2, 3],
       [6, 7]])

A slice is not a new array, but a limited reference to the original array

In [32]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
b = a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [35]:
b[0, 0] = 55
print(b)
print(a)

[[55  3]
 [ 6  7]]
[[ 1 55  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


You can mix indexing  with slicing: you get an array with less rank

In [38]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
print(a[1, :])
print(a[1])

[5 6 7 8]
[5 6 7 8]


In [40]:
print(a[:,2])

[ 3  7 11]


In [41]:
print(a.shape)
print(a[2, :].shape)
print(a[:, 2].shape)

(3, 4)
(4,)
(3,)


Select by array of indexes

In [43]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
print("***")
idxs = np.array([0, 2, 0, 1])
print(a[:,idxs])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
***
[[ 1  3  1  2]
 [ 4  6  4  5]
 [ 7  9  7  8]
 [10 12 10 11]]


Idem with rows

In [46]:
print(a)
print(idxs)
print("*" * 10)
print(a[idxs, :])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[0 2 0 1]
**********
[[1 2 3]
 [7 8 9]
 [1 2 3]
 [4 5 6]]


Select elements by their indexes

In [47]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
idx1 = [0, 1, 2, 1]
idx2 = [2, 0, 1, 0]
a[idx1, idx2]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([3, 4, 8, 4])

Since the referred elements are references to the original ones, you can change them through the slice.

In [48]:
a[idx1, idx2] += 10
print(a)

[[ 1  2 13]
 [14  5  6]
 [ 7 18  9]
 [10 11 12]]


Selecting elements by using boolean arrays

In [50]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
bool_idx = a % 2 == 0 
print(bool_idx)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[False  True False]
 [ True False  True]
 [False  True False]
 [ True False  True]]


Now we can use the boolean array to select elements in the other array

In [51]:
print(a[bool_idx])

[ 2  4  6  8 10 12]


So you can modify those elements

In [52]:
a[bool_idx] *= 2
print(a)

[[ 1  4  3]
 [ 8  5 12]
 [ 7 16  9]
 [20 11 24]]


Note: You can mix arrays in operations

In [54]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.random.random((4, 3))
print(a)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[0.49692082 0.83480254 0.44970846]
 [0.39389396 0.52292992 0.18605059]
 [0.31233241 0.67207044 0.0128383 ]
 [0.81781985 0.45675008 0.71423326]]


In [55]:
a[b < 0.5] += 19
print(a)

[[20  2 22]
 [23  5 25]
 [26  8 28]
 [10 30 12]]


To use multiple AND conditions, we use the operator &

In [59]:
a[(b > 0.2) & (b < 0.5)]

array([20, 22, 23, 26, 30])

For OR conditions, we use the otperator |

In [60]:
a[(b < 0.2) | (b > 0.5)]

array([ 2,  5, 25,  8, 28, 10, 12])

If you do not provide a data type, numpy infer the array type by the initialization parameters

In [62]:
x = np.array([1, 2])
print(x.dtype)

int64


In [63]:
y = np.array([1.0, 2.0])
print(y.dtype)

float64


In [64]:
z = np.array([True, False])
print(z.dtype)

bool


You can specify the array type by using parameter _dtype_

In [65]:
z = np.array([1, 2], dtype=np.float64)
print(z.dtype)
print(z)

float64
[1. 2.]


## Operations with arrays

In [66]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [67]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [68]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


Note: This are all element-wise operations

In [69]:
print(x-y)  # np.substract
print(x*y)  # np.multiply
print(x/y)  # np.divide
print(np.sqrt(x))
print(np.power(x, y))

[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]


You can get the full list of operations here: https://numpy.org/doc/stable/reference/routines.math.html

Inner product:

In [73]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [74]:
print(v)
print(w)
v.dot(w)

[ 9 10]
[11 12]


219

In [75]:
print(x)
print(v)
x.dot(v)

[[1 2]
 [3 4]]
[ 9 10]


array([29, 67])

In [76]:
print(x)
print(y)
x.dot(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

Axis-wise operations

In [81]:
x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))

[[1 2]
 [3 4]]
10


In [82]:
print(np.sum(x, axis=0))

[4 6]


In [83]:
print(np.sum(x, axis=1))

[3 7]


That works on matrixes of any number of dimensions

In [86]:
x = np.array([[[2, 1, 2, 5], [4,2, 5, 2], [9, 8, 7, 6]], [[3,5, 4, 1], [8, 9, 2, 6], [0,1, 8, 8]]])
print(x)
print(x.shape)

[[[2 1 2 5]
  [4 2 5 2]
  [9 8 7 6]]

 [[3 5 4 1]
  [8 9 2 6]
  [0 1 8 8]]]
(2, 3, 4)


In [87]:
print(np.sum(x))

108


In [89]:
print(np.sum(x, axis=0))

[[ 5  6  6  6]
 [12 11  7  8]
 [ 9  9 15 14]]


In [90]:
print(np.sum(x, axis=1))

[[15 11 14 13]
 [11 15 14 15]]


In [91]:
print(np.sum(x, axis=2))

[[10 13 30]
 [13 25 17]]


You can also do operations on collection of axis

In [93]:
print(x)
print(np.sum(x, axis=(0,1)))

[[[2 1 2 5]
  [4 2 5 2]
  [9 8 7 6]]

 [[3 5 4 1]
  [8 9 2 6]
  [0 1 8 8]]]
[26 26 28 28]


In [94]:
print(np.sum(x, axis=(0,2)))
print(np.sum(x, axis=(1, 2)))

[23 38 47]
[53 55]


Transpose

In [95]:
x = np.array([[1,2,3], [4, 5, 6]])
print(x)
print(x.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


Horizontal and vertical stacking

In [97]:
a = np.array([[2, 3], [5, 6]])
b = np.array([[4, 3], [7, 9], [1, 6]])
c = np.array([[4, 5, 6], [7, 6, 5]])

In [98]:
print(a)
print(b)
print(np.vstack([a,b]))

[[2 3]
 [5 6]]
[[4 3]
 [7 9]
 [1 6]]
[[2 3]
 [5 6]
 [4 3]
 [7 9]
 [1 6]]


In [99]:
print(a)
print(c)
print(np.hstack([a,c]))

[[2 3]
 [5 6]]
[[4 5 6]
 [7 6 5]]
[[2 3 4 5 6]
 [5 6 7 6 5]]


Operator similar to the ternary operator

In [100]:
a = np.array(range(5,15))
print(a)
np.where(a > 7, a, a-5)

[ 5  6  7  8  9 10 11 12 13 14]


array([ 0,  1,  2,  8,  9, 10, 11, 12, 13, 14])

If only one parameter is provided, it return the indexes of the True values

In [101]:
np.where(a % 2 == 0)

(array([1, 3, 5, 7, 9]),)

## Array reshaping
Note: Neither values nor value order are modified

In [103]:
a = np.array(range(0, 24))
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [104]:
b = a.reshape((2,12))
print(b)
print(b.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
(2, 12)


The number of elements must be the same

In [105]:
a.reshape((3, 2))

ValueError: cannot reshape array of size 24 into shape (3,2)

Providing -1 in a dimension makes numpy to automatically calculate the value

In [106]:
a.reshape((3,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [107]:
a.reshape((-1, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

You can only use a single -1 per operation

In [108]:
a.reshape((-1, 2, -1))

ValueError: can only specify one unknown dimension

You can also reshape on a different number of dimensions

In [109]:
a.reshape((2, -1, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

### Broadcasting
Broadcasting is a powerful feature in NumPy that enables efficient array operations on arrays of different shapes and sizes. 

It allows for implicit element-wise operations between arrays, even if their shapes are not identical. 

Broadcasting eliminates the need for explicit loops, resulting in concise and efficient code.

Lets start with an example. Supose you want to add a row vector to every row in a matrix

In [111]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x)
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


In [110]:
y = np.empty_like(x)  # empty array with the same structure than x

for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


There is another solution that avoid using the for loop: Build a new matrix tiling the row vector horizontally

In [112]:
vv = np.tile(v, (4, 1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [113]:
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This is the way broadcasting work, doing matrix modifications automatically

In [114]:
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

**Broadcasting rules**
- Array extension: If the arrays have different shapes, NumPy extends the smaller array by adding dimensions with size 1 to match the shape of the larger array. This extension is virtual and doesn't require actually replicating the data.

In [115]:
print(x.shape)
print(v.shape)

(4, 3)
(3,)


In this case, a one is added to the smallest array, so it finally is (4,3) and (1,3)

- Dimensions compatibility: For two arrays to be compatible for broadcasting, their dimensions must either match or one of them must have a size of 1. If an array has a size of 1 along a particular dimension, it is stretched or repeated along that dimension to match the size of the other array.

In [118]:
# Compatibles
a = np.random.random((3, 4, 1))
b = np.random.random((3, 1, 4))
c = a+b

In [119]:
# Incompatibles
a = np.random.random((3, 4, 1))
b = np.random.random((3, 2, 4))
c = a+b

ValueError: operands could not be broadcast together with shapes (3,4,1) (3,2,4) 

- Element-wise operation: Once the arrays have compatible shapes, NumPy performs element-wise operations between them. Operations are applied independently to each element of the arrays.

In [120]:
a = np.random.random((3, 4, 1))
b = np.random.random((1, 1, 5))
(a+b).shape

(3, 4, 5)

**Note**: No actual dupplication is performed. Every transformation is virtual.

Some examples:

In [121]:
a = np.ones((3, 4))
b = np.ones((3, 1))*3
print(a)
print(b)
a+b

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[3.]
 [3.]
 [3.]]


array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [125]:
a = np.ones(4)
b = np.ones((3, 4))*5
print(a)
print(b)
a+b

[1. 1. 1. 1.]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [126]:
a = np.ones((1, 4))
b = np.ones((3, 1))*6
print(a)
print(b)
a+b

[[1. 1. 1. 1.]]
[[6.]
 [6.]
 [6.]]


array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

To learn more or debugging, you can directly get the broadcast result.

In [127]:
print(np.broadcast_to(a, ((3,4))))
print(np.broadcast_to(b, ((3, 4))))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


Functions that support broadcasting are known as **universal functions**. There is a very complete collection of those functions.

Here some examples:

In [128]:
# Add a constant to an array
a = np.random.random((4, 3))
print(a)
print(a + 4)

[[0.32460151 0.12158484 0.1397481 ]
 [0.52761216 0.69166833 0.75964068]
 [0.76558543 0.15103348 0.05155056]
 [0.26471519 0.40257923 0.75281193]]
[[4.32460151 4.12158484 4.1397481 ]
 [4.52761216 4.69166833 4.75964068]
 [4.76558543 4.15103348 4.05155056]
 [4.26471519 4.40257923 4.75281193]]


In [129]:
np.broadcast_to(4, (4, 3))

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [130]:
np.array(4).shape

()

Normalize a matrix by removing the mean value

In [132]:
a = np.random.randint(1, 10, size=(4,3))
print(a)

[[6 7 7]
 [3 2 9]
 [7 3 5]
 [9 6 5]]


In [134]:
mean = np.average(a, axis=0)
print(mean)

[6.25 4.5  6.5 ]


In [136]:
print(a - mean)

[[-0.25  2.5   0.5 ]
 [-3.25 -2.5   2.5 ]
 [ 0.75 -1.5  -1.5 ]
 [ 2.75  1.5  -1.5 ]]


In [137]:
print(np.sum(a-mean))

0.0


Uniformize matrix values using (x-min)/(max-min)

In [138]:
a = np.random.randint(1, 10, size=(4,3))
print(a)

[[6 7 3]
 [7 1 9]
 [8 1 9]
 [3 7 6]]


In [139]:
mx = np.max(a)
mn = np.min(a)
print((a-mn)/(mx-mn))

[[0.625 0.75  0.25 ]
 [0.75  0.    1.   ]
 [0.875 0.    1.   ]
 [0.25  0.75  0.625]]


Create a multiplication table.

In [140]:
x = np.array(range(1, 11))
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [141]:
x = x[:, np.newaxis]
print(x)
print(x.T)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [142]:
x*x.T

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

More complex example, matrix of euclidean distances between pair of points

In [143]:
coords = np.array([(2, 3), (4, 5), (-1,8), (0, 3)])
x1 = coords[:, np.newaxis, :]
x2 = coords[np.newaxis, :, :]
print(x1)

[[[ 2  3]]

 [[ 4  5]]

 [[-1  8]]

 [[ 0  3]]]


In [144]:
print(x2)

[[[ 2  3]
  [ 4  5]
  [-1  8]
  [ 0  3]]]


In [145]:
print(x1.shape)
print(x2.shape)

(4, 1, 2)
(1, 4, 2)


In [146]:
np.broadcast_to(x1, (4, 4, 2))

array([[[ 2,  3],
        [ 2,  3],
        [ 2,  3],
        [ 2,  3]],

       [[ 4,  5],
        [ 4,  5],
        [ 4,  5],
        [ 4,  5]],

       [[-1,  8],
        [-1,  8],
        [-1,  8],
        [-1,  8]],

       [[ 0,  3],
        [ 0,  3],
        [ 0,  3],
        [ 0,  3]]])

In [147]:
np.broadcast_to(x2, (4, 4, 2))

array([[[ 2,  3],
        [ 4,  5],
        [-1,  8],
        [ 0,  3]],

       [[ 2,  3],
        [ 4,  5],
        [-1,  8],
        [ 0,  3]],

       [[ 2,  3],
        [ 4,  5],
        [-1,  8],
        [ 0,  3]],

       [[ 2,  3],
        [ 4,  5],
        [-1,  8],
        [ 0,  3]]])

In [148]:
np.sqrt(np.sum((x1 - x2)**2, axis=-1))

array([[0.        , 2.82842712, 5.83095189, 2.        ],
       [2.82842712, 0.        , 5.83095189, 4.47213595],
       [5.83095189, 5.83095189, 0.        , 5.09901951],
       [2.        , 4.47213595, 5.09901951, 0.        ]])

# Solved Exercises

**Exercise**. Create a one dimensional array with numbers from 0 to 9

In [149]:
print(np.arange(0,10))
print(np.array(range(0,10)))
print(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


**Exercise**. Create a boolean array of 3x3 with all values in True

In [152]:
print(np.full((3,3), True, dtype=bool))
print(np.zeros((3,3)) == 0)
print(np.ones((3,3), dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Exercise**. Extract all the odd numbers fro a 1D array

In [154]:
arr = np.arange(0,10)
print(arr)
arr[arr % 2 == 1]

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

**Exercise**. Replace all negative numbers in an array by constant 33

In [155]:
arr = np.random.randint(-10, 10, size=(10))
print(arr)
arr[arr < 0] = 33
print(arr)

[ 9 -1  3 -5  3 -8  7  9  7  0]
[ 9 33  3 33  3 33  7  9  7  0]


**Exercise**. Replace all positive numbers by -5, but withoug changing the original array

In [156]:
arr = np.random.randint(-10, 10, size=(10))
print(arr)
np.where(arr > 0, -5, arr)

[-2  5 -2  7 -5  1  3  2 -8  7]


array([-2, -5, -2, -5, -5, -5, -5, -5, -8, -5])

**Exercise**. Replace a 1D array with numbers from 1 to 10 into a 2D array with two rows

In [157]:
# 5. Convierta un arreglo 1D con los numeros del 1 al 10 en otro 2D con dos filas
a = np.arange(1, 11)
a.reshape((-1, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**Exercise**. Stack two arrays vertically and two arrays horizontally

In [158]:
a = np.ones((3, 2))
b = np.ones((4, 2)) * 2
c = np.ones((3, 5)) * 3
print(np.hstack([a, c]))
print(np.vstack([a, b]))

[[1. 1. 3. 3. 3. 3. 3.]
 [1. 1. 3. 3. 3. 3. 3.]
 [1. 1. 3. 3. 3. 3. 3.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


**Exercise**. Starting from the array [1, 2, 3], generate the following array transforming a using numpy functions:
[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [160]:
a = np.array([1, 2, 3])
out = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

np.hstack([
    np.vstack([a, a, a]).T.reshape((1, -1))[0],
    a, a, a])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Like most things in Python that looks complex, there is a better way of doing it

In [161]:
np.r_[np.repeat(a,3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

**Exercise**. Find the positions where two arrays match

In [165]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

**Exercise**. From a numpy array get a subarray with values between 5 and 10, both included

In [166]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[np.where((5 <= a) & (a <= 10))]

array([ 6,  9, 10])

**Exercise**. Swap the first and second row of an array

In [168]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[[1, 0, 2], :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


**Exercise**. Swap the last two columns from an array

In [170]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, [0, 2, 1]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


**Exercise**. Invert the rows of a numpy array.

In [173]:
arr = np.arange(16).reshape(4,4)
print(arr)
arr[np.arange(3, -1, -1), :]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

As usual, there is a simpler solution

In [175]:
arr[::-1, :]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

**Exercise**. Invert the columns from a numpy array

In [177]:
arr = np.arange(16).reshape(4,4)
print(arr)
print(arr[:,::-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


**Exercise**. Create a numpy array with 1 in the border and 0 in the inside

In [178]:
def cuad(size):
    a = np.ones(size)
    a[1:-1,1:-1] = 0
    return a

cuad((4, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

**Exercise**. Create a padding of 0 around a 2D array.

In [179]:
a = np.arange(9).reshape(3,3)
print(a)
r,c = a.shape
b = np.zeros((r+2, c+2))
b[1:-1, 1:-1] = a
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 0.]
 [0. 3. 4. 5. 0.]
 [0. 6. 7. 8. 0.]
 [0. 0. 0. 0. 0.]]


This is a so common operation that already has a numpy function for that, having many more optons

In [184]:
np.pad(a, pad_width=1, mode='constant', constant_values=0)

array([[0, 0, 0, 0, 0],
       [0, 0, 1, 2, 0],
       [0, 3, 4, 5, 0],
       [0, 6, 7, 8, 0],
       [0, 0, 0, 0, 0]])

**Exercise**. Create a square 5x5 matrix with values 1, 2, 3, ... just below the diagonal.

In [192]:
a = np.zeros((5, 5), dtype=int)
for idx in range(4):
    a[idx+1, idx] = idx + 1
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

There is a simpler way using np.diag

In [197]:
np.diag(range(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**Exercise**. Create a 8x8 matrix with a chessboard-like structure

In [45]:
(np.arange(0,81).reshape((9,-1)) % 2)[:8,:8]

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

There are many other solutions, like this one

In [198]:
a = np.ones((8,8))
a[::2,::2] = 0
a[1::2,1::2] = 0
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

The same using np.tile

In [199]:
np.tile([1, 0], 36).reshape((-1, 9))[:, :-1]

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

Other with np.tile

In [200]:
np.tile([[0, 1],[1,0]], (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**Exercise**. Normalize a 5x5 array

In [202]:
arr = np.random.random((5,5))
m = np.mean(arr)
st = np.std(arr)
norm = (arr - m)/st
print(norm)

[[ 0.79319212  1.11490928  1.0740123  -1.33645257  0.70465325]
 [-1.87412037  0.60459742  0.36317626  0.35800222  0.95086675]
 [-0.65458865 -0.77147867  1.0878553  -0.65568534  0.11699032]
 [-0.2557065  -1.17881771 -1.76774791  1.2127547   1.34891586]
 [ 0.95114783  0.17385669  0.01501575 -0.75619523 -1.61915306]]


**Exercise**. In a 1D array, find the oposite (-x) of the elements between 3 and 8

In [203]:
arr = np.arange(1, 14)
arr[(arr >= 3)&(arr <=8)] *= -1
arr

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13])

**Exercise**. Create a 5x5 matrix with values in the rows from 1 to 4

In [204]:
arr = np.zeros((5, 5))
arr + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

doing broadcast by hand:

In [206]:
np.tile(np.arange(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

**Exercise**. Create a vector of size 10 with x-distant values between 0 and 1, both excluded

In [209]:
(np.arange(0,11)*(1/11))[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

there is a numpy function for that

In [211]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

**Exercise**. A matrix contains cartesian coordinates. Convert them to polar coordinates.

In [213]:
cart = np.random.random((5,2))
print(cart)

x, y = cart[:,0], cart[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y, x)
np.hstack([r[:,np.newaxis], t[:, np.newaxis]])

[[0.91970977 0.79243561]
 [0.48987371 0.43600286]
 [0.00334765 0.83958714]
 [0.82941152 0.22431476]
 [0.98885016 0.19359945]]


array([[1.21400999, 0.71119856],
       [0.65580084, 0.72728007],
       [0.83959381, 1.56680909],
       [0.85920927, 0.26413167],
       [1.00762364, 0.1933369 ]])

**Exercise**. Create a random vector and substitute the maximum value by 0

Hint: use the np.argmax function

In [214]:
v = np.random.random(10)
print(v)
v[np.argmax(v)] = 0
v

[0.84036843 0.83799785 0.28955445 0.68200849 0.95667029 0.69232624
 0.11228948 0.37968504 0.98526196 0.95298598]


array([0.84036843, 0.83799785, 0.28955445, 0.68200849, 0.95667029,
       0.69232624, 0.11228948, 0.37968504, 0.        , 0.95298598])

**Exercise**. Find the value closer to a given value in a random array

In [216]:
arr = np.random.randint(0,100, size=(20))
v = 15
print(arr)
arr[np.argmin(np.abs(arr - v))]

[31 75 36 63 86 61 25  1  0 16 11 82  3 69  0 24 31 83  5 28]


16

**Exercise**. Build an array of positions that uniformly cover the area [0,1]x[0,1]

In [217]:
delta = 5
import itertools as it
np.array(list(it.product(range(0,delta), range(0, delta)))) / (delta - 1)

array([[0.  , 0.  ],
       [0.  , 0.25],
       [0.  , 0.5 ],
       [0.  , 0.75],
       [0.  , 1.  ],
       [0.25, 0.  ],
       [0.25, 0.25],
       [0.25, 0.5 ],
       [0.25, 0.75],
       [0.25, 1.  ],
       [0.5 , 0.  ],
       [0.5 , 0.25],
       [0.5 , 0.5 ],
       [0.5 , 0.75],
       [0.5 , 1.  ],
       [0.75, 0.  ],
       [0.75, 0.25],
       [0.75, 0.5 ],
       [0.75, 0.75],
       [0.75, 1.  ],
       [1.  , 0.  ],
       [1.  , 0.25],
       [1.  , 0.5 ],
       [1.  , 0.75],
       [1.  , 1.  ]])

There is numpy function for doing something similar.

In [218]:
delta = 5
x, y = np.meshgrid(np.linspace(0,1,delta), np.linspace(0,1,delta))
x,y

(array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ],
        [0.  , 0.25, 0.5 , 0.75, 1.  ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.25, 0.25, 0.25, 0.25, 0.25],
        [0.5 , 0.5 , 0.5 , 0.5 , 0.5 ],
        [0.75, 0.75, 0.75, 0.75, 0.75],
        [1.  , 1.  , 1.  , 1.  , 1.  ]]))

This way of returning values is very handy for many applications, like function evaluation

In [219]:
np.sin(x**2 + y**2)

array([[0.        , 0.06245932, 0.24740396, 0.53330267, 0.84147098],
       [0.06245932, 0.12467473, 0.30743851, 0.58509727, 0.87357494],
       [0.24740396, 0.30743851, 0.47942554, 0.72600866, 0.94898462],
       [0.53330267, 0.58509727, 0.72600866, 0.90226759, 0.99996559],
       [0.84147098, 0.87357494, 0.94898462, 0.99996559, 0.90929743]])

In [220]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
# 29. Dado un arreglo de 4 dimensiones, conviertalo en un arreglo de 3 dimensiones colapsando las dos ultimas en 1
arr = np.arange(48).reshape((2, 3, 4, 2))
print(arr)
arr2 = arr.reshape(arr.shape[:-2]+(-1,))
print(arr2)

In [ ]:
# 30. Considere el vector [1,2,3,4,5]. Como hacemos un nuevo vector insertando 3 ceros consecutivos 
# entre cada uno de estos valores
x = np.array([1, 2, 3, 4, 5])
nz = 6
np.hstack([x[:,np.newaxis], np.zeros((5, nz))]).reshape((1,-1))

In [ ]:
# otra solución
result = np.zeros(len(x)+(len(x)-1)*nz)
result[::nz+1] = x
result